### ISSUE TITLE
deepsleep

### ISSUE THREAD

**Issue by maba64** [robotzero1/esp32cam-timelapse#2]
Hello 
Thank you for sharing the code-
Would it be possible to install a deepsleep function (to safe batterie) and save the current photo Number in the Eprom?

thank you verry much

Markus

**Comment by robotzero1** [comment]
Hi,
Here's another project that has deepsleep - https://github.com/dimhoff/ESP32-CAM_Interval it's much more complicated than my code so you could either just upload it or combine the deepsleep parts into my code.

For Eprom.. this is easy with the Preferences library - https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/src/Preferences.h 

Cheers,
Andrew

**Comment by maba64** [comment]
Thank you very much for your support
