### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by whoim2** [robotzero1/esp32cam-timelapse#3]
Hello! Esp32cam with your examples may stream and save photos to sd on external trigger one time?
Its need for use on 3d printer. Stream connected to RRF (duet) web control page, photos take on change layer from motheboard pin, ttl level, via gcode command.
Sorry, bad speak english.
I need use two examples, stream and save to sd, in one scenario. Esp may this?

**Comment by robotzero1** [comment]
Hi! I've got the first draft of what you want here: https://github.com/robotzero1/esp32cam-3d-printer-monitor

There's quite a few improvements to be made but for me it's basically working. Pin13 has to be kept low until you want a photo saved to the card. When it goes high a picture is taken.

I'm not sure how you connect this to your board. If I have time, I'll make some improvements and test it with my Ender 3

**Comment by whoim2** [comment]
Thanks!

**Comment by whoim2** [comment]
> Hi! I've got the first draft of what you want here: https://github.com/robotzero1/esp32cam-3d-printer-monitor
> 
> There's quite a few improvements to be made but for me it's basically working. Pin13 has to be kept low until you want a photo saved to the card. When it goes high a picture is taken.
> 
> I'm not sure how you connect this to your board. If I have time, I'll make some improvements and test it with my Ender 3

see my php-script for you-based sketch)
generate gifs and movies from esp32cam
https://github.com/whoim2/esp32cam-timelaps-php-gallery

**Comment by robotzero1** [comment]
Looks like it works well!
